### ISSUE TITLE
Error while building package

### ISSUE THREAD

**Issue by NoobJsPerson** [termux/termux-create-package#31]
When i tried to build my package i got this error
```
Building termux-fetch_0.1_all.deb
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/termux-create-package", line 134, in <module>
    create_debfile(output_debfile_name, package_tmp_directory.name)
  File "/data/data/com.termux/files/usr/bin/termux-create-package", line 101, in create_debfile
    subprocess.check_call(["ar", 'r', debfile_output,
  File "/data/data/com.termux/files/usr/lib/python3.9/subprocess.py", line 368, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.9/subprocess.py", line 349, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/data/data/com.termux/files/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/data/data/com.termux/files/usr/lib/python3.9/subprocess.py", line 1819, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ar'
```

**Comment by xeffyr** [comment]
Install `binutils` - it provides "ar" utility.
